### ISSUE TITLE
🚀 [Feature] Better URL structure of the Frontend

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#104]
## :rocket: Feature

Better URL structure of the Frontend
- [X] URLs have # in them
- [X] Double Redirect is not caught and produce errors in console.log
- [ ] Figure out how we can properly integrate into nginx (in the future the frontend must be reachable under `/` now it must be reachable under `/vue/`

**Comment by einhornimmond** [comment]
To make frontend reachable under / is easy, the real problem is to make community-server reachable not under /
I have already tryed everything which was suggested here:
https://stackoverflow.com/questions/2119736/cakephp-in-a-subdirectory-using-nginx-rewrite-rules

The only way I see is to load vue-frontend inside a cakephp side which I can set via routing to /
But last time I tryed to explain it to alex he didn't understand me. 
In past I had put vue-client inside community-server and edited package.js and public/index.html so that on build a cakephp suitable side in template/pages/frontend.ctp was generated which was loading the vue-frontend and was accessable via /
But I don't know how to make it that Alex can work with automatic rebuild how he is used to it with that configuration. 
I couldn't find a way for build vue with watch how I do it with mithril-js
(watchify ./src/app.js  -t [ babelify --presets [ @babel/preset-env ] ] -o app.js -v)

**Comment by ulfgebhardt** [comment]
#35

**Comment by Mogge** [comment]
See this: https://router.vuejs.org/guide/essentials/history-mode.html#nginx

**Comment by ulfgebhardt** [comment]
@Mogge Whats with the remaining issues?
