### ISSUE TITLE
🚀 [Feature] Serve vue-client from login-server

### ISSUE THREAD

**Issue by einhornimmond** [gradido/gradido#121]
## :rocket: Feature
Serve all js and css files which belong to vue-client (and maybe additional ressources) 
via login-server

### Advantages
- better security because login-server can check if vue-client wasn't change via build-in hash
- better performance, because login-server can serve it precompressed (better compression rates) from memory

### Implementation
- Put path to vue-client-data into config
- load by start all vue data into memory and compress them with maximum compression rate
- Find a way to automaticlly store hashes from vue js files on every build in login-server binary
- Put contents of js and css files directly into requested page (index.html) together with csrf token
- use header to prevent external js load (<meta http-equiv="Content-Security-Policy" content="script-src 'self'"\>)

## Additional Context
I always think about how we can make it really secure.
Until now my way was to input passwords only on from login-server rendered static html pages to prevent every form of javascript based hacking. 
But I think the same security can be archieved with js-frontend served directly from login-server, checked via hash if it wasn't changed, inserted direct in returned html and disallow dynamic loading of additional js. 

With that I don't see a problem anymore if user put there passwords into vue-client forms. 
And we don't need complicated redirections I currently use for community-server.

**Comment by ulfgebhardt** [comment]
The task of the login server is to handle login stuff. What you describe is the task of nginx, the webserver. None of our server should be involved in compression related tasks, there is software we can use to check integrity of a webapp a custom system is not needed

**Comment by ulfgebhardt** [comment]
> I always think about how we can make it really secure.
> Until now my way was to input passwords only on from login-server rendered static html pages to prevent every form of javascript based hacking.
> But I think the same security can be archieved with js-frontend served directly from login-server, checked via hash if it wasn't changed, inserted direct in returned html and disallow dynamic loading of additional js.

I believe this is a question of definition. We cannot take responsibility for the network "we can only communicate over the internet if there is no thugs" or the client "we can only accept communications from clients which are not hacked" since its just beyond our control. Therefore we should undergo a certain amount of measures to ensure we deliver an uncorrupted client software to the user. In the end it does not matter since the client can get corrupted on the way to the client or on the client machine and therefore can not be trusted anyways.
We have to make sure to have every client input properly validated and rely on technics like ssl to make it hard for attackers to change network traffic on the way from client to server. If we assume that we then claim the user is responsible to have an uncorrupted machine, this will leave us with the identity problem to solve. How can we be sure that the user is the user he claims to be. This problem can only be solved by other external systems like 2-Factor-Authentification, which bring their own problems like transport security. Assuming now we don't want to solve the identity problem for now, all measures proposed in this issue potentially strengthen the likelyness to deliver an uncorrupted client, but do not ensure its integrity towards the user and do not solve the identity problem. Therefore the security increase is zero.

**Comment by ulfgebhardt** [comment]
Closing this in favor of:
- #132 
- #131 
- #130 
- #129
