### ISSUE TITLE
💬 [Question] Logdatei Gradido

### ISSUE THREAD

**Issue by ogerly** [gradido/gradido#1210]
Welche Logadatein wollen wir speichern 

## 💬 Question
Folgende Functionen stehen  zur Verfügung und könnten geloggt werden. 

Wallet: 
- [ ] User registriert
- [ ] User registriert e-mail bestätigt. 

User Transaktion 
- [ ] gesendet
- [ ] empfangen

Userdaten geändert
- [ ] Vor- und Nachname
- [ ] Passwort
- [ ] Sprache
- [ ] Newsletter
- [ ] Coinanimation

Admin:
- [ ] Aktivitäten bestätigen zur Schöpfung
- [ ] Schöpfung einreichen für einen User
- [ ] Schöpfung bestätigen 
- [ ] Schöpfung zurückweisen 
- [ ] E Mail bestätigen neu senden

**Comment by ulfgebhardt** [comment]
We should use general History utilities. This could be either one of those:
- https://www.npmjs.com/package/@anchan828/typeorm-history
- https://github.com/ephillipe/typeorm-revisions

I suggest `createdAt` and `updatedAt` columns, which seem to be part of the standard of typeorm'
. https://stackoverflow.com/questions/64941148/node-js-add-created-at-and-updated-at-in-entity-of-typeorm

Furthermore we should use soft delete for specific tables with a typeorm feature also natively implemented `@DeleteDateColumn`
- https://github.com/typeorm/typeorm/commit/5b50f474034a570d3e209e15a6dc8f25fab73739

Besides all the database magic we should also implement a log framework which will save the applications log to a file (may already be covered with pm2).
There should be a sql log for everything happening since the last database backup. Typeorm offers tools for this, whereof the documentation can be found here:
- https://orkhan.gitbook.io/typeorm/docs/logging

To answer your question @ogerly : I think we should solve those issues more generally on a database level and not with custom build features. We surely should utilize the data generated by those generalized solutions to show the users/admin the changes/deletes etc. in the Frontend tho.
