### ISSUE TITLE
🔧 [Refactor] Authentication handled by the backend

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#13]
## :zap: Refactor ticket

It is part of http standard to set cookies from the backend and handle all authentication via this retransmitted cookie. This is not the case for us as far as I understand it. Therefore it will not be possible to safely remember a user. This might be by design?

### Motive

Use web standards

**Comment by einhornimmond** [comment]
Login-Server save the session-id in a cookie which than is readed from community-server.
That is also the reason why I had make a branch "merged_with_backend" in which I have insert the vue-wallet in community-server so that the js would be loaded by a page which was rendered from community-server and contains the session-id from the cookie and also the csfr code from community-server. 
Alex start in his development the vue-wallet from a separat server which than cannot read my cookie, so I also return the session_id with the login request. 
If you know how to get Alex dev-setup to read the cookies from login-server, that would be nice.

**Comment by ulfgebhardt** [comment]
Normally authentication is completely done by the server in the background. All the client does is sending the cookie with each request.
The server does:
1. Set the cookie
2. Validate the cookie value
3. Redirect the user if needed (e.g. no longer logged in)

We can not do that since it seems you use a completely different model. This will require a lot of hacks on the client and might lead to unsolvavale situation(we can not determined if the user is still logged in since we would have to handle this on every call).

For now I suggest to just keep going as we currently do and get things running. (I will make a deployment issue for you so you can try and deploy the current setup on a staging machine). I believe getting it running is more important at the moment. Lo g term we have to redactor the service to handle authentication validation etc on the server

**Comment by einhornimmond** [comment]
Login-Server does exactly that: 
1. Set the cookie after login (try it out, with the old backend) with name GRADIDO_LOGIN
2. What do do you exactly mean with validate? The session_id contains a random number which I use to index the session object in Login-Server Memory in a map-container (src/SingletonManager/SessionManager.cpp line 337). So on every page-call on Login-Server he reads the session-cookie to use the correct session. 
On Community-Server pages he reads also the cookie and use the session-ids for the ajax requests to login-server. 
Because community-server pages make the requests server-side from server IP I cannot use cookie directly. But with js client it should work, if he is started from the same domain:port to have access to the cookie. 
3. Community-Server does exactly that, redirect to login-server if you not logged in. 
If you start docker-composer and go to http://localhost you will be redirected to http://localhost/account
also to login-server login-page. The same is true for other community-server pages like http://localhost/transaction-send-coins/create

Oh I see, until before by ajax login the session cookie wasn't set, but with my last change it should be.
