### ISSUE TITLE
🐛 [Bug] Password reset form does not work properly

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#1302]
## 🐛 Bugreport

![image.png](https://images.zenhubusercontent.com/5ca1e741e2f21b570ab87e6e/0d56a3f7-da41-4d8b-abcd-68bc2173276d)

`
Nachdem ich erstmal nur oben das Passwort eingegeben hatte, konnte ich auf “Passwort festlegen” klicken (nicht ausgegraut) und gelangte zum Login.

Ich bin dann mit dem Browser auf die Seite zurückgegangen, habe dann auch das Passwort beides Mal gesetzt und erhalte Fehlermeldung.

Der Versuch, über den E-Mail-Bestätigungslink erneut zu bestätigen, schlug fehl.

Dann habe ich mich nochmal registriert und eine Bestätigungsmail bekommen. Konnte auch bestätigen, aber beim Versuch, mich einzuloggen, kommt Fehlermeldung:
`

![image](https://user-images.githubusercontent.com/1238238/149883558-3dee5d69-05e8-4d02-8f0b-3b3b91c5ae39.png)

Ich kann mich als user nicht mehr mit meiner E-Mail-Adresse registrieren.

- Always redirect to login even on error
- Password must not be confirmed

Furthermore:
- Do we want to implement a call to verify the validity of an verification code?
- Give the user the option to request another?

**Comment by Elweyn** [comment]
Hi @ulfgebhardt, @BerndHueckstaedt,

I looked at this issue on my local maschin and get the same behavior... I think that the problem comes from the fact that we use an underling component to imput the passwords, in this component their is a check that looks if the user have inputed the same password.
So this should be refactored: frontend/src/components/inputs/InputPasswordConfirmation.vue, frontend/src/views/Pages/ResetPassword.vue.

I have done something on my local machin but the confirmation button is never
