### ISSUE TITLE
🐛 [Bug] Docker not building

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#14]
## :bug: Bugreport

![image](https://user-images.githubusercontent.com/1238238/109216244-90144c00-77b4-11eb-80d0-b75030885cb9.png)

**Comment by ulfgebhardt** [comment]
For now I have commented the `gradido node` build out of `docker-compose`

**Comment by paulsj-80** [comment]
This is because I am using env variables to give container names + refer volume on host. Idea is that single host can launch multiple nodes, each with a different instance folder. I am launching them like this:
sudo GN_INSTANCE_FOLDER=/var/usr/gradido/docker-instances/0 GN_CONTAINER_NAME=insta_0 docker-compose run gradido-node

**Comment by paulsj-80** [comment]
Would it be possible to include env variables when building?

**Comment by ulfgebhardt** [comment]
`docker-compose` should run without env variables

-> There is a scale command to scale applications

https://docs.docker.com/compose/reference/scale/
https://medium.com/@karthi.net/how-to-scale-services-using-docker-compose-31d7b83a6648
https://stackoverflow.com/questions/39663096/docker-compose-creating-multiple-instances-for-the-same-image
