### ISSUE TITLE
🔧 [Refactor] Passwort has restrictions

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#16]
## :zap: Refactor ticket

For some reason the password is restricted to character requirements:

![image](https://user-images.githubusercontent.com/1238238/109227880-4da53c00-77c1-11eb-959a-a3cb3ab4b17d.png)

I'd really like to use my standard password `1234` ... why can I not do that?

**Comment by einhornimmond** [comment]
The Role of login-server is to securely store the private keys for the gdd-accounts. 
It does that by create a encryption key with sha256 and argon2 from email and password and encrypt the private key with that. 
The parameter for argon2 choosed relativly low so that server don't use to much CPU. 
But with that it is only save with passwords which not easy to guess, so that a brute-force attack needs far to many tries to be effcient without a supercomputer. 
The target is to prevent misusing of private keys even if hacker gets access to server and therefore to the db. 
So that even less experienced admins can host Login-Server without the need of thinking to much of security. 
A part for this concept is currently missing. Give the login-server instance a own security code which cannot be accessed by hacking server as additional part to private key encryption, With that it weren't possible for hackers getting to the private key even if they get/guess some passwords and have access to db. But I haven't found a way yet to archieve that simple and secure.

**Comment by einhornimmond** [comment]
But I could add a option unsecure.allowEveryPasswords

**Comment by einhornimmond** [comment]
The choosen special character a because of problems with some special chars in regExp in C++ (._.);
I'd like to use all special chars.

**Comment by einhornimmond** [comment]
added a option: unsecure.allow_all_passwords which allow every password even empty ones

**Comment by ulfgebhardt** [comment]
![image](https://user-images.githubusercontent.com/1238238/109320786-b4256b00-7850-11eb-92c9-bde922d85396.png)
Passt zum thema
