### ISSUE TITLE
💥 [DevOps] Backend Test For AdminResolvers `confirm two creations one after …` Is Flaky

### ISSUE THREAD

**Issue by Tirokk** [gradido/gradido#1939]
## 💥 DevOps ticket

Backend test for `AdminResolvers.ts` `confirm two creations one after …` is flaky.

- local for the developer
- in GitHub Actions

### Problem

Sometimes we get this error in the test:

<img width="1837" alt="Bildschirmfoto 2022-05-19 um 18 44 33" src="https://user-images.githubusercontent.com/25344101/170228085-dc3dbd41-6ac4-4c82-8832-5f68bc257bcb.png">

**Comment by Mogge** [comment]
We do want that test to be fixed, e.g. the test should throw an error, so that we can remove it,
See #1886

**Comment by clauspeterhuebner** [comment]
i had several ideas to solve this problem:
- introduce milliseconds in datetime columns to ensure correct order even when writing in the same second
- enable the database to lock single row instead of whole table during write access by defining indexes; described here: https://stackoverflow.com/questions/2332768/how-to-avoid-mysql-deadlock-found-when-trying-to-get-lock-try-restarting-trans
- surround the write access with a retry logic to solve deadlocks of concurrent invocations of the same method; described here: https://blog.tekenlight.com/2019/02/21/database-deadlock-mysql.html

All three ideas are implemented, but not till the third one with the retry logic solves the problem
