### ISSUE TITLE
💥 [DevOps] Cleanup branches

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#27]
## 💥 DevOps ticket

Please clean up the branches on `graido_login_server` and `gradido_community_server`. For me it is not clear whats currently deployed, what is the next thing we want to deploy and furthermore what lies further in the future. Furthermore there is two master branches. I would love to have exactly one which is also named `master`

![image](https://user-images.githubusercontent.com/1238238/109590761-d77c3e80-7b0c-11eb-8811-56a4ea4a032a.png)

### Motive

Clarify what is what, simplification

### Additional resources

- `login_server` branches: https://github.com/gradido/gradido_login_server/branches/all
- `community_server`branches: https://github.com/gradido/gradido_login_server/branches/all

**Comment by einhornimmond** [comment]
Ok, I have 
- deleted login-server branches, 
- add 2 tags,
- rename branches: 
  - stage0 == master (current live version on gdd1.gradido.com)
  - stage1 version with docker and prepared for vue, live on stage1.gradido.net
  - stage2 version with hedera, live on staging.gradido.net
- keep debug branch because deadlock error isn't fixed yet

**Comment by einhornimmond** [comment]
Ok, community-server branches cleaned
- stage0 is current live version on gdd1.gradido.com
- stage1 is version with docker and prepared for vue, live on stage1.gradido.net
- stage2 == master version with using gn, live on staging,gradido.net and staging2.gradido.net,

**Comment by ulfgebhardt** [comment]
thanks <3
