### ISSUE TITLE
🐛 [Bug] 0,01 GDD missing and no Decay

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#439]
## 🐛 Bugreport

Transaction list of new user:
- Recieved 10GDD
Its the only transaction, no decay transaction displayed

Balance of the Account: 9,99 GDD

This might be solved by the ceil issue described here: #434

**Comment by ulfgebhardt** [comment]
@einhornimmond is this still an issue?

**Comment by einhornimmond** [comment]
Yes, because of the removing of decays less than 0.01 GDD.
For example:
receiving 10 GDD in reality 100000 GDD Cent,
Now decay kicked in and there 99999 GDD Cent or 9,99 GDD left. 

Calculated decay is 1 GDD Cent or 0.0001 GDD but my code remove anything smaller than 100 or 0.01
Should I remove this code and let every decay pass? With ceil even a decay value of 0.0001 will be shown as 0.01.

For the condition that user must be able to send all GDD he gets shown as balance, we must do it. 
But it could lead to confusion if nearly anytime there will be shown a decay of at least 0.01 GDD.
Maybe in longterm we need more informations for the user how much the decay is exactly.
