### ISSUE TITLE
🐛 [Bug] PM2 doest restart on deploy

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#781]
## 🐛 Bugreport

@einhornimmond said that the PM2 process running the backend (apollo) server is not restarting properly when deploying a new version on staging.

Is this still the case?
What is/was the probem?
How can we ensure we will not have it again?

**Comment by einhornimmond** [comment]
I have fixed it so far.
I use nvm (https://github.com/nvm-sh/nvm) for node and npm version managing. That makes it easy to use different node versions parallel. Also it is easy to install a specific node version.
Bad it is not good for scripting. Because in scripts you must call the binaries with her complete path (or add the path manually), as you should have seen in build_frontend.sh
So I have update the call to pm2 with the complete path, and now it should work.
