### ISSUE TITLE
💬 [Question] Clarify Protocol and Contents of Communication between Communities

### ISSUE THREAD

**Issue by ulfgebhardt** [gradido/gradido#870]
## 💬 Question

We decided that we will try the federation Approach. This only solves the Problem to get to know other communities. It is still to clarify what information we want to exchange and how.
I suggest that we use a direct connection to the community, since every communication on a federation channel is public. The inter-community traffic might be private hence this notion.

We need to exchange Infos about the Community:
- Where to Register
- Name
- Member Count
- Website
- ...

Those information are public, but there might also be some more private calls we want to make, which is not available to everyone e.G sendCoins. This function might be wise to require an admin approve a community to before coins are accepted in oder to avoid tempering and cheating. This will create "namespaces" or  "coloredCoins" within Gradido. Not all Communities can trade with eachother.

There is many more questions regarding inter community communications. One pressing matter is the protocol. Do we just query the graphqlEndpoint or do we define/use other standards? Do we define stuff like protocol version on top of graphql?

**Comment by BerndHueckstaedt** [comment]
»This function might be wise to require an admin approve a community to before coins are accepted in oder to avoid tempering and cheating. This will create "namespaces" or "coloredCoins" within Gradido. Not all Communities can trade with eachother.«

I think we should leave the decision to the individual user which "coloredGradidos" he accepts. Because it's not communities that trade with each other, but users.

This can probably be handled via white lists and black lists.
If the communication is handled directly from community to community, the transaction could go something like this:

- The payer asks for the black / white list of the payee.
- This is automatically sent as a reply.
- with this information the payer selects in his wallet the coloredGradidos he wants to and can pay with (according to the Black/Whitelist).
- he sends the Gradidos.
- the recipient confirms the receipt automatically.

**Comment by clauspeterhuebner** [comment]
These questions have to be answered in a "community communitcation concept" as business requirements. The detailed technical solutions have afterwards be described in the corresponding technical design document.
Lets start with the business view in ticket #

**Comment by clauspeterhuebner** [comment]
The business point of view is ready for review.
The technical details for federation are still open and a task by @Elweyn (Hannes ?!?!?!)
So on my opinion this ticket can be closed, @ulfgebhardt  correct?
